type: object
description: Details of any tenant-wide Reassignment Configurations (eg. enabled/disabled)
properties:
  disabled:
    type: boolean
    nullable: true
    description: Flag to determine if Reassignment Configuration is enabled or disabled for a tenant.  When this flag is set to true, Reassignment Configuration is disabled.
    default: false
    example: true