get:
  operationId: getDefaultIdentityAttributeConfig
  tags:
    - Identity Profiles
  summary: Get default identity attribute config
  description: >-
    This returns the default identity attribute config.
  parameters:
    - in: path
      name: identity-profile-id
      schema:
        type: string
        format: uuid
      required: true
      x-sailpoint-resource-operation-id: listIdentityProfiles
      description: The Identity Profile ID.
      example: 2b838de9-db9b-abcf-e646-d4f274ad4238
  responses:
    '200':
      description: An Identity Attribute Config object.
      content:
        application/json:
          schema:
            $ref: '../schemas/IdentityAttributeConfig.yaml'
    '400':
      $ref: '../responses/400.yaml'
    '401':
      $ref: '../responses/401.yaml'
    '403':
      $ref: '../responses/403.yaml'
    '404':
      $ref: '../responses/404.yaml'
    '429':
      $ref: '../responses/429.yaml'
    '500':
      $ref: '../responses/500.yaml'
  security:
    - userAuth: [idn:identity-profile:manage]
  x-sailpoint-userLevels:
    - ORG_ADMIN