get:
  operationId: getReassignmentConfigTypes
  tags:
  - Work Reassignment
  summary: List reassignment config types
  description: Gets a collection of types which are available in the Reassignment
    Configuration UI.
  security:
  - userAuth:
    - idn:reassignment-configuration:read
  responses:
    '200':
      description: List of Reassignment Configuration Types
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: ../schemas/work-reassignment/ConfigType.yaml
    '400':
      $ref: ../responses/400.yaml
    '401':
      $ref: ../responses/401.yaml
    '403':
      $ref: ../responses/403.yaml
    '429':
      $ref: ../responses/429.yaml
    '500':
      $ref: ../responses/500.yaml
  parameters:
  - name: X-SailPoint-Experimental
    in: header
    description: Use this header to enable this experimental API.
    example: true
    schema:
      type: string
      default: true
    required: true
