get:
  operationId: getSingleSearchAttributeConfig
  tags:
  - Search Attribute Configuration
  summary: Get extended search attribute
  security:
    - userAuth: []
  x-sailpoint-userLevels:
    - ORG_ADMIN
  description: >-
    Get an extended attribute configuration by name.
  parameters:
  - name: name
    in: path
    description: Name of the extended search attribute configuration to get.
    required: true
    schema:
      type: string
      example: newMailAttribute
  - name: X-SailPoint-Experimental
    in: header
    description: Use this header to enable this experimental API.
    example: true
    schema:
      type: string
      default: true
    required: true
  responses:
    '200':
      description: Specific attribute configuration in IdentityNow.
      content:
        application/json:
          schema:
            $ref: ../schemas/SearchAttributeConfig.yaml
    '204':
      $ref: ../responses/204.yaml
    '401':
      $ref: ../responses/401.yaml
    '403':
      $ref: ../responses/403.yaml
    '404':
      $ref: ../responses/404.yaml
    '429':
      $ref: ../responses/429.yaml
    '500':
      $ref: ../responses/500.yaml
delete:
  operationId: deleteSearchAttributeConfig
  tags:
  - Search Attribute Configuration
  summary: Delete extended search attribute
  security:
    - userAuth: []
  x-sailpoint-userLevels:
    - ORG_ADMIN
  description: >-
    Delete an extended attribute configuration by name.
  parameters:
  - name: name
    in: path
    description: Name of the extended search attribute configuration to delete.
    required: true
    schema:
      type: string
      example: newMailAttribute
  - name: X-SailPoint-Experimental
    in: header
    description: Use this header to enable this experimental API.
    example: true
    schema:
      type: string
      default: true
    required: true
  responses:
    '204':
      $ref: ../responses/204.yaml
    '401':
      $ref: ../responses/401.yaml
    '403':
      $ref: ../responses/403.yaml
    '404':
      $ref: ../responses/404.yaml
    '429':
      $ref: ../responses/429.yaml
    '500':
      $ref: ../responses/500.yaml
patch:
  operationId: patchSearchAttributeConfig
  tags:
  - Search Attribute Configuration
  summary: Update extended search attribute
  security:
    - userAuth: []
  x-sailpoint-userLevels:
    - ORG_ADMIN
  description: >-
    Update an existing search attribute configuration. 
    
    You can patch these fields:

    * name 
    * displayName
    * applicationAttributes
  parameters:
  - name: name
    in: path
    description: Name of the search attribute configuration to patch.
    required: true
    schema:
      type: string
      example: promotedMailAttribute
  - name: X-SailPoint-Experimental
    in: header
    description: Use this header to enable this experimental API.
    example: true
    schema:
      type: string
      default: true
    required: true
  requestBody:
    content:
      application/json-patch+json:
        schema:
          type: array
          items:
            $ref: ../schemas/JsonPatchOperation.yaml
        example:
        - op: replace
          path: /name
          value: newAttributeName
        - op: replace
          path: /displayName
          value: new attribute display name
        - op: add
          path: /applicationAttributes
          value:
            2c91808b79fd2422017a0b35d30f3968: employeeNumber
    required: true
  responses:
    '200':
      description: Responds with the search attribute configuration as updated.
      content:
        application/json:
          schema:
            $ref: ../schemas/SearchAttributeConfig.yaml
    '400':
      $ref: ../responses/400.yaml
    '401':
      $ref: ../responses/401.yaml
    '403':
      $ref: ../responses/403.yaml
    '404':
      $ref: ../responses/404.yaml
    '429':
      $ref: ../responses/429.yaml
    '500':
      $ref: ../responses/500.yaml
