get:
  operationId: getSourceConfig
  tags:
  - Sources
  summary: Gets source config with language-translations
  security:
    - userAuth: []
  x-sailpoint-userLevels:
    - ORG_ADMIN
  description: >-
    Looks up and returns the source config for the requested source id
    after populating the source config values and applying language translations.
  parameters:
  - in: path
    name: id
    schema:
      type: string
    required: true
    x-sailpoint-resource-operation-id: listSources
    description: The Source id
    example: cef3ee201db947c5912551015ba0c679
  - in: query
    name: locale
    schema:
      type: string
      enum:
      - de
      - false
      - fi
      - sv
      - ru
      - pt
      - ko
      - zh-TW
      - en
      - it
      - fr
      - zh-CN
      - hu
      - es
      - cs
      - ja
      - pl
      - da
      - nl
    description: The locale to apply to the config. If no viable locale is given,
      it will default to "en"
    example: en
    required: false
  responses:
    '200':
      description: A Connector Detail object
      content:
        application/json:
          schema:
            $ref: ../schemas/ConnectorDetail.yaml
    '400':
      $ref: ../responses/400.yaml
    '401':
      $ref: ../responses/401.yaml
    '403':
      $ref: ../responses/403.yaml
    '404':
      $ref: ../responses/404.yaml
    '429':
      $ref: ../responses/429.yaml
    '500':
      $ref: ../responses/500.yaml
