get:
  operationId: getSpConfigImport
  security:
    - userAuth: [sp:config:manage]
  x-sailpoint-userLevels:
    - ORG_ADMIN
  tags:
  - SP-Config
  summary: Download import job result
  description: 'This gets import file resulting from the import job with the requested
    id and downloads it to a file. The downloaded file will contain the results of
    the import operation, including any error, warning or informational messages associated
    with the import.

    The request will need the following security scope:

    - sp:config:manage'
  parameters:
  - in: path
    name: id
    schema:
      type: string
    required: true
    x-sailpoint-resource-operation-id: importSpConfig
    description: The ID of the import job whose results will be downloaded.
    example: ef38f94347e94562b5bb8424a56397d8
  responses:
    '200':
      description: Import results JSON object, containing detailed results of the
        import operation.
      content:
        application/json:
          schema:
            $ref: ../schemas/SpConfigImportResults.yaml
    '400':
      $ref: ../responses/400.yaml
    '401':
      $ref: ../responses/401.yaml
    '403':
      $ref: ../responses/403.yaml
    '404':
      $ref: ../responses/404.yaml
    '429':
      $ref: ../responses/429.yaml
    '500':
      $ref: ../responses/500.yaml
