import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
import {
  versionCrumb,
  versionSelector,
} from 'docusaurus-plugin-openapi-docs/lib/sidebars/utils';
import nermVersions from './docs/api/nerm/v2025/versions.json';

const sidebars: SidebarsConfig = {
  openApiSidebar: [
    {
      type: 'category',
      label: 'Documentation',
      collapsible: false,
      link: {type: 'doc', id: 'docs'},
      items: [
        {
          type: 'category',
          label: 'Extensibility',
          link: {type: 'doc', id: 'extensibility'},
          items: [{type: 'autogenerated', dirName: 'extensibility'}],
        },
        {
          type: 'category',
          label: 'Connectivity',
          link: {type: 'doc', id: 'connectivity'},
          items: [{type: 'autogenerated', dirName: 'connectivity'}],
        },
        {
          type: 'category',
          label: 'Tools',
          link: {type: 'doc', id: 'tools'},
          items: [{type: 'autogenerated', dirName: 'tools'}],
        },
        {
          type: 'category',
          label: 'Reporting',
          link: {type: 'doc', id: 'reporting'},
          items: [{type: 'autogenerated', dirName: 'reporting'}],
        },
        {
          type: 'category',
          label: 'Guides',
          link: {type: 'doc', id: 'guides'},
          items: [{type: 'autogenerated', dirName: 'guides'}],
        },
        {
          type: 'link',
          label: 'Product Documentation',
          href: 'https://documentation.sailpoint.com',
        },
      ],
    },
  ],
  iiqSideBar: [
    {
      type: 'category',
      label: 'Documentation',
      collapsible: false,
      link: {type: 'doc', id: 'iiq'},
      items: [
        {
          type: 'category',
          label: 'Plugin Developer Guide',
          link: {type: 'doc', id: 'plugin-developer-guide'},
          items: [
            {type: 'autogenerated', dirName: 'iiq/plugin-developer-guide'},
          ],
        },
        {
          type: 'link',
          label: 'Product Documentation',
          href: 'https://documentation.sailpoint.com/#identityiq',
        },
      ],
    },
  ],
  iiqApiSideBar: [
    {
      type: 'category',
      label: 'API Specifications',
      collapsible: false,
      link: {
        type: 'generated-index',
        title: 'API Specifications',
        description:
          "These are the SCIM APIs for SailPoint's on-premise service, IdentityIQ. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.",
        slug: '/api/iiq',
      },
      items: require('./docs/api/iiq/sidebar.ts'),
    },
  ],
  nerm_2025_sidebar: [
    {
      type: 'html',
      defaultStyle: true,
      value: versionSelector(nermVersions),
      className: 'version-button',
    },
    {
      type: 'html',
      defaultStyle: true,
      value: versionCrumb(`v2025`),
    },
    {
      type: 'doc',
      id: 'api/nerm/v2025/getting-started',
    },
    {
      type: 'doc',
      id: 'api/nerm/v2025/authentication',
    },
    {
      type: 'doc',
      id: 'api/nerm/v2025/pagination-filtering',
    },
    {
      type: 'category',
      label: 'NERM v2025 APIs',
      link: {
        type: 'generated-index',
        title: 'NERM v2025 APIs',
        description:
          'These are the Non-employee Risk Management APIs for SailPoint.',
        slug: '/api/nerm/v2025',
      },
      items: require('./docs/api/nerm/v2025/sidebar.ts'),
    },
  ],
  nermSideBar: [
    {
      type: 'html',
      defaultStyle: true,
      value: versionSelector(nermVersions),
      className: 'version-button',
    },
    {
      type: 'html',
      defaultStyle: true,
      value: versionCrumb(`v1`), // or dynamically detect the current version
    },
    {
      type: 'doc',
      id: 'api/nerm/v1/getting-started',
    },
    {
      type: 'doc',
      id: 'api/nerm/v1/authentication',
    },
    {
      type: 'doc',
      id: 'api/nerm/v1/pagination-metadata-filtering',
    },
    {
      type: 'category',
      label: 'NERM v1 API',
      link: {
        type: 'generated-index',
        title: 'NERM v1 API',
        description:
          'These are the Non-employee Risk Management APIs for SailPoint. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.',
        slug: '/api/nerm/v1',
      },
      items: require('./docs/api/nerm/v1/sidebar.ts'),
    },
  ],
  isc_api_sidebar: [
    {
      type: 'doc',
      id: 'api/getting-started',
    },
    {
      type: 'doc',
      id: 'api/authentication',
    },
    {
      type: 'doc',
      id: 'api/authorization',
    },
    {
      type: 'doc',
      id: 'api/api-versioning-strategy',
    },
    {
      type: 'doc',
      id: 'api/api-versioning-migration',
    },
    {
      type: 'doc',
      id: 'api/standard-collection-parameters',
    },
    {
      type: 'doc',
      id: 'api/rate-limit',
    },
    {
      type: 'doc',
      id: 'api/postman-collections',
    },
    {
      type: 'doc',
      id: 'api/patch-requests',
    },
    {
      type: 'category',
      label: 'API Specifications',
      link: {
        type: 'generated-index',
        title: 'API Specifications',
        description:
          'Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.',
        slug: '/api',
      },
      items: require('./docs/api/sidebar.ts'),
    },
  ],
    communityPoliciesSidebar: [
    {
      type: 'category',
      label: 'Community policies',
      collapsible: false,
      link: { type: 'doc', id: 'community-policies' },
      items: [
        { type: 'doc', id: 'ai-policy', label: 'AI Usage Policy' },
        { type: 'doc', id: 'community-code-of-conduct', label: 'Developer Community Code of Conduct' },
        { type: 'doc', id: 'event-code-of-conduct', label: 'Developer Community Event Code of Conduct' },
        { type: 'doc', id: 'ambassador-code-of-conduct', label: 'Ambassador Code of Conduct' },
        { type: 'doc', id: 'ambassador-agreement', label: 'Ambassador Program Agreement' },
      ],
    },
  ],
};

export default sidebars;
