import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Extensibility minified sidebar config — includes docs/*, extensibility, connectivity,
// tools (excluding Reference folders), reporting, guides, and iiq.
// All API sidebars (isc, iiq-api, nerm) are intentionally omitted.
const sidebars: SidebarsConfig = {
  openApiSidebar: [
    {
      type: 'category',
      label: 'Identity Security Cloud documentation',
      collapsible: false,
      link: {type: 'doc', id: 'docs'},
      items: [
        {
          type: 'category',
          label: 'Extensibility',
          link: {type: 'doc', id: 'extensibility'},
          items: [{type: 'autogenerated', dirName: 'extensibility'}],
        },
        {
          type: 'category',
          label: 'Connectivity',
          link: {type: 'doc', id: 'connectivity'},
          items: [{type: 'autogenerated', dirName: 'connectivity'}],
        },
        {
          type: 'category',
          label: 'Tools',
          link: {type: 'doc', id: 'tools'},
          items: [{type: 'autogenerated', dirName: 'tools'}],
        },
        {
          type: 'category',
          label: 'Reporting',
          link: {type: 'doc', id: 'reporting'},
          items: [{type: 'autogenerated', dirName: 'reporting'}],
        },
        {
          type: 'category',
          label: 'Solution guides',
          link: {type: 'doc', id: 'guides'},
          items: [{type: 'autogenerated', dirName: 'guides'}],
        },
        {
          type: 'link',
          label: 'SailPoint product documentation',
          href: 'https://documentation.sailpoint.com',
        },
      ],
    },
  ],
  iiqSideBar: [
    {
      type: 'category',
      label: 'IdentityIQ documentation',
      collapsible: false,
      link: {type: 'doc', id: 'iiq'},
      items: [
        {
          type: 'category',
          label: 'IdentityIQ plugin developer guide',
          link: {type: 'doc', id: 'plugin-developer-guide'},
          items: [
            {type: 'autogenerated', dirName: 'iiq/plugin-developer-guide'},
          ],
        },
        {
          type: 'link',
          label: 'SailPoint product documentation',
          href: 'https://documentation.sailpoint.com/#identityiq',
        },
      ],
    },
  ],
};

export default sidebars;
