/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: 'idn_docs'}],
  openApiSidebar: [
    {
      type: "category",
      label: "IDN V3",
      link: {
        type: "generated-index",
        title: "IDN V3",
        description:
          "These are the public APIs for SailPoint's SaaS services. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.",
        slug: "/category/identity-now-api"
      },
      // @ts-ignore
      items: require("./docs/sailpoint-api-v3/sidebar.js")
    },
    {
      type: "category",
      label: "IDN Beta",
      link: {
        type: "generated-index",
        title: "IDN Beta",
        description:
          "These are the public APIs for SailPoint's SaaS services. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.",
        slug: "/category/identity-now-api"
      },
      // @ts-ignore
      items: require("./docs/sailpoint-api-beta/sidebar.js")
    }
  ]
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
