import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Extensibility minified sidebar config — includes docs/*, extensibility, connectivity,
// tools (excluding Reference folders), reporting, guides, and iiq.
// All API sidebars (isc, iiq-api, nerm) are intentionally omitted.
const sidebars: SidebarsConfig = {
  openApiSidebar: [
    {
      type: 'category',
      label: 'Documentation',
      collapsible: false,
      link: {type: 'doc', id: 'docs'},
      items: [
        {
          type: 'category',
          label: 'Extensibility',
          link: {type: 'doc', id: 'extensibility'},
          items: [{type: 'autogenerated', dirName: 'extensibility'}],
        },
        {
          type: 'category',
          label: 'Connectivity',
          link: {type: 'doc', id: 'connectivity'},
          items: [{type: 'autogenerated', dirName: 'connectivity'}],
        },
        {
          type: 'category',
          label: 'Tools',
          link: {type: 'doc', id: 'tools'},
          items: [{type: 'autogenerated', dirName: 'tools'}],
        },
        {
          type: 'category',
          label: 'Reporting',
          link: {type: 'doc', id: 'reporting'},
          items: [{type: 'autogenerated', dirName: 'reporting'}],
        },
        {
          type: 'category',
          label: 'Guides',
          link: {type: 'doc', id: 'guides'},
          items: [{type: 'autogenerated', dirName: 'guides'}],
        },
        {
          type: 'link',
          label: 'Product Documentation',
          href: 'https://documentation.sailpoint.com',
        },
      ],
    },
  ],
  iiqSideBar: [
    {
      type: 'category',
      label: 'Documentation',
      collapsible: false,
      link: {type: 'doc', id: 'iiq'},
      items: [
        {
          type: 'category',
          label: 'Plugin Developer Guide',
          link: {type: 'doc', id: 'plugin-developer-guide'},
          items: [
            {type: 'autogenerated', dirName: 'iiq/plugin-developer-guide'},
          ],
        },
        {
          type: 'link',
          label: 'Product Documentation',
          href: 'https://documentation.sailpoint.com/#identityiq',
        },
      ],
    },
  ],
  communityPoliciesSidebar: [
    {
      type: 'category',
      label: 'Community policies',
      collapsible: false,
      link: { type: 'doc', id: 'community-policies' },
      items: [
        { type: 'doc', id: 'ai-policy', label: 'AI Usage Policy' },
        { type: 'doc', id: 'community-code-of-conduct', label: 'Community Code of Conduct' },
        { type: 'doc', id: 'event-code-of-conduct', label: 'Event Code of Conduct' },
        { type: 'doc', id: 'ambassador-agreement', label: 'Ambassador Program Agreement' },
        { type: 'doc', id: 'ambassador-code-of-conduct', label: 'Ambassador Code of Conduct' }
      ],
    },
  ],
};

export default sidebars;
