get:
  operationId: getMFADuoConfig
  tags:
    - MFA Configuration
  summary: Configuration of duo mfa method
  description: >-
    This API returns the configuration of an Duo MFA method.
  security:
    - userAuth: [idn:mfa-configuration:read, idn:mfa-configuration:manage]
  x-sailpoint-userLevels:
    - ORG_ADMIN
  responses:
    "200":
      description: The configuration of an Duo MFA method.
      content:
        application/json:
          schema:
            $ref: "../schemas/MfaDuoConfig.yaml"
          example:
            {
              "mfaMethod": "duo-web",
              "enabled": true,
              "host": "www.example.com",
              "accessKey": "d******Y",
              "identityAttribute": "email",
              "configProperties": {
                "skey": "6******B",
                "ikey": "Q123WE45R6TY7890ZXCV"
              }
            }
    "400":
      $ref: "../responses/400.yaml"
    "401":
      $ref: "../responses/401.yaml"
    "403":
      $ref: "../responses/403.yaml"
    "429":
      $ref: "../responses/429.yaml"
    "500":
      $ref: "../responses/500.yaml"

put:
  operationId: setMFADuoConfig
  tags:
    - MFA Configuration
  summary: Set duo mfa configuration
  description: >-
    This API sets the configuration of an Duo MFA method.
  security:
    - userAuth: [idn:mfa-configuration:manage]
  x-sailpoint-userLevels:
    - ORG_ADMIN
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../schemas/MfaDuoConfig.yaml"
        example:
          {
            "mfaMethod": "duo-web",
            "enabled": true,
            "host": "www.example.com",
            "accessKey": "qw123Y3QlA5UqocYpdU3rEkzrK2D497y",
            "identityAttribute": "email",
            "configProperties": {
              "skey": "12q3WERlcUHWJmiMqyCXI3uOF7EaDJTbdeOp6E2B",
              "ikey": "Q123WE45R6TY7890ZXCV"
            }
          }
  responses:
    "200":
      description: MFA configuration of an Duo MFA method.
      content:
        application/json:
          schema:
            $ref: "../schemas/MfaDuoConfig.yaml"
          example:
            {
              "mfaMethod": "duo-web",
              "enabled": true,
              "host": "www.example.com",
              "accessKey": "q******y",
              "identityAttribute": "email",
              "configProperties": {
                "skey": "1******B",
                "ikey": "Q123WE45R6TY7890ZXCV"
              }
            }
    "400":
      $ref: "../responses/400.yaml"
    "401":
      $ref: "../responses/401.yaml"
    "403":
      $ref: "../responses/403.yaml"
    "429":
      $ref: "../responses/429.yaml"
    "500":
      $ref: "../responses/500.yaml"
