get:
  operationId: listReassignmentConfigurations
  tags:
  - Work Reassignment
  summary: List reassignment configurations
  description: Gets all Reassignment configuration for the current org.
  security:
  - userAuth:
    - idn:reassignment-configuration:read
  responses:
    '200':
      description: A list of Reassignment Configurations for an org
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: ../schemas/work-reassignment/ConfigurationResponse.yaml
    '400':
      $ref: ../responses/400.yaml
    '401':
      $ref: ../responses/401.yaml
    '403':
      $ref: ../responses/403.yaml
    '404':
      $ref: ../responses/404.yaml
    '429':
      $ref: ../responses/429.yaml
    '500':
      $ref: ../responses/500.yaml
  parameters:
  - name: X-SailPoint-Experimental
    in: header
    description: Use this header to enable this experimental API.
    example: true
    schema:
      type: string
      default: true
    required: true
post:
  operationId: createReassignmentConfiguration
  tags:
  - Work Reassignment
  summary: Create a reassignment configuration
  description: Creates a new Reassignment Configuration for the specified identity.
  security:
  - userAuth:
    - idn:reassignment-configuration:create
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../schemas/work-reassignment/ConfigurationItemRequest.yaml
  responses:
    '201':
      description: The newly created Reassignment Configuration object
      content:
        application/json:
          schema:
            $ref: ../schemas/work-reassignment/ConfigurationItemResponse.yaml
    '400':
      $ref: ../responses/400.yaml
    '401':
      $ref: ../responses/401.yaml
    '403':
      $ref: ../responses/403.yaml
    '429':
      $ref: ../responses/429.yaml
    '500':
      $ref: ../responses/500.yaml
  parameters:
  - name: X-SailPoint-Experimental
    in: header
    description: Use this header to enable this experimental API.
    example: true
    schema:
      type: string
      default: true
    required: true
