post:
  summary: Upload csv to discover applications
  tags:
  - Application Discovery
  description: |-
    Uploading a CSV file with application data for manual correlation to specific ISC connectors. 
    If a suitable ISC connector is unavailable, the system will recommend generic connectors instead.
  security:
  - userAuth:
    - idn:application-discovery:write
  - applicationAuth:
    - idn:application-discovery:write
  operationId: sendManualDiscoverApplicationsCsvTemplateV1
  requestBody:
    content:
      multipart/form-data:
        schema:
          $ref: ../schemas/manualdiscoverapplications.yaml
  responses:
    '200':
      description: The CSV has been successfully processed.
    '400':
      $ref: ../../shared/responses/400.yaml
      description: >
        Bad request - There was an error with the CSV format or validation failed (e.g., `application_name` missing).
        Error message should be provided in response.
    '401':
      $ref: ../../shared/responses/401.yaml
    '403':
      $ref: ../../shared/responses/403.yaml
    '429':
      $ref: ../../shared/responses/429.yaml
    '500':
      $ref: ../../shared/responses/500.yaml
