
type: object
title: Attr Sync Source Config
description: Specification of attribute sync configuration for a source
required:
  - source
  - attributes
properties:
  source:
    $ref: './AttrSyncSource.yaml'
  attributes:
    type: array
    description: Attribute synchronization configuration for specific identity attributes in the context of a source
    items:
      $ref: './AttrSyncSourceAttributeConfig.yaml'
    example: [
      {
        name: 'email',
        displayName: 'Email',
        enabled: true,
        target: 'mail'
      },
      {
        name: 'firstname',
        displayName: 'First Name',
        enabled: false,
        target: 'givenName'
      }
    ]
