description: Client Runtime Logging Configuration
title: Set Expiration Date
nullable: true
type: object
required:
  - rootLevel
properties:
  clientId:
    description: Log configuration's client ID
    type: string
    example: 3a38a51992e8445ab51a549c0a70ee66
  expiration:
    description: Expiration date-time of the log configuration request.  Can be no greater than 24 hours from current date-time.
    example: "2024-11-06T01:31:08.013164Z"
    type: string
    format: date-time
  rootLevel:
    description: Root log level to apply, the default level for all logs. For more information about logging levels, refer to the "Logging Levels" table in [Enabling Connector Logging in IdentityNow](https://community.sailpoint.com/t5/IdentityNow-Articles/Enabling-Connector-Logging-in-IdentityNow/ta-p/188107).
    default: INFO
    example: INFO
    $ref: './StandardLevel.yaml'
  logLevels:
    description: Map of log level by key. The keys are logging classes, and the values are logging levels. To see the available connectors and their logging classes, refer to the "Logging Classes" table in [Enabling Connector Logging in IdentityNow](https://community.sailpoint.com/t5/IdentityNow-Articles/Enabling-Connector-Logging-in-IdentityNow/ta-p/188107).
    example: {
        "sailpoint.connector.ADLDAPConnector": "TRACE",
        "sailpoint.connector.JDBCConnector": "DEBUG"
    }
    $ref: './LogLevelSpec.yaml'
