openapi: 3.0.1
info:
  title: Identity Security Cloud API - Service Desk Integration
  description: >-
    Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with
    greater scalability. We encourage you to join the SailPoint Developer Community forum at
    https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
  termsOfService: https://developer.sailpoint.com/discuss/tos
  contact:
    name: Developer Relations
    url: https://developer.sailpoint.com/discuss/api-help
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: v1
servers:
  - url: https://{tenant}.api.identitynow.com
    description: This is the production API server.
    variables:
      tenant:
        default: sailpoint
        description: This is the name of your tenant, typically your company's name.
  - url: https://{apiUrl}
    description: This is the versioned API server.
    variables:
      apiUrl:
        default: sailpoint.api.identitynow.com
        description: This is the api url of your tenant
tags:
  - name: Service Desk Integration
    description: >
      Use this API to build an integration between Identity Security Cloud and a service desk ITSM (IT service
      management) solution. 

      Once an administrator builds this integration between Identity Security Cloud and a service desk, users can use
      Identity Security Cloud to raise and track tickets that are synchronized between Identity Security Cloud and the
      service desk. 


      In Identity Security Cloud, administrators can create a service desk integration (sometimes also called an SDIM,
      or Service Desk Integration Module) by going to Admin > Connections > Service Desk and selecting 'Create.'


      To create a Generic Service Desk integration, for example, administrators must provide the required information on
      the General Settings page, the Connectivity and Authentication information, Ticket Creation information, Status
      Mapping information, and Requester Source information on the Configure page. 

      Refer to [Integrating SailPoint with Generic Service
      Desk](https://documentation.sailpoint.com/connectors/generic_sd/help/integrating_generic_service_desk/intro.html)
      for more information about the process of setting up a Generic Service Desk in Identity Security Cloud.


      Administrators can create various service desk integrations, all with their own nuances. 

      The following service desk integrations are available: 


      - [Atlassian Cloud Jira Service
      Management](https://documentation.sailpoint.com/connectors/atlassian/jira_cloud/help/integrating_jira_cloud_sd/introduction.html)


      - [Atlassian Server Jira Service
      Management](https://documentation.sailpoint.com/connectors/atlassian/jira_server/help/integrating_jira_server_sd/introduction.html)


      - [BMC Helix ITSM Service
      Desk](https://documentation.sailpoint.com/connectors/bmc/helix_ITSM_sd/help/integrating_bmc_helix_itsm_sd/intro.html)


      - [BMC Helix Remedyforce Service
      Desk](https://documentation.sailpoint.com/connectors/bmc/helix_remedyforce_sd/help/integrating_bmc_helix_remedyforce_sd/intro.html)


      - [Generic Service
      Desk](https://documentation.sailpoint.com/connectors/generic_sd/help/integrating_generic_service_desk/intro.html)


      - [ServiceNow Service
      Desk](https://documentation.sailpoint.com/connectors/servicenow/sdim/help/integrating_servicenow_sdim/intro.html)


      - [Zendesk Service
      Desk](https://documentation.sailpoint.com/connectors/zendesk/help/integrating_zendesk_sd/introduction.html)
paths:
  /service-desk-integrations/v1:
    $ref: ./paths/service-desk-integrations-v1.yaml
  /service-desk-integrations/v1/{id}:
    $ref: ./paths/service-desk-integrations-v1-by-id.yaml
  /service-desk-integrations/v1/types:
    $ref: ./paths/service-desk-integrations-v1-types.yaml
  /service-desk-integrations/v1/templates/{scriptName}:
    $ref: ./paths/service-desk-integrations-v1-templates-by-scriptname.yaml
  /service-desk-integrations/v1/status-check-configuration:
    $ref: ./paths/service-desk-integrations-v1-status-check-configuration.yaml
security:
  - userAuth:
      - sp:scopes:all
