type: object
title: Recommendation Config Dto
properties:
  recommenderFeatures:
    type: array
    items:
      type: string
    description: List of identity attributes to use for calculating certification recommendations
    example: ["jobTitle", "location", "peer_group", "department", "active"]
  peerGroupPercentageThreshold:
    type: number
    description: The percent value that the recommendation calculation must surpass to produce a YES recommendation
    minimum: 0.0
    maximum: 1.0
    format: float
    example: 0.5
  runAutoSelectOnce:
    type: boolean
    description: If true, rulesRecommenderConfig will be refreshed with new programatically selected attribute and threshold values on the next pipeline run
    default: false
    example: false
  onlyTuneThreshold:
    type: boolean
    description: If true, rulesRecommenderConfig will be refreshed with new programatically selected threshold values on the next pipeline run
    default: false
    example: false