title: Object Configuration Model
description: Response model for object configuration.
type: object
properties:
  objectType:
    type: string
    description: >-
      Object type the configuration is for.
    example: "TRIGGER_SUBSCRIPTION"
  referenceExtractors:
    type: array
    nullable: true
    description: >-
      List of JSON paths within an exported object of this type, representing references that must be resolved.
    items:
      type: string
    example: ["$.owner"]
  signatureRequired:
    type: boolean
    default: false
    description: >-
      Indicates whether this type of object will be JWS signed and cannot be modified before import.
    example: false
  alwaysResolveById:
    type: boolean
    default: false
    description: Indicates whether this object type must be always be resolved by ID.
    example: true
  legacyObject:
    type: boolean
    default: false
    description: Indicates whether this is a legacy object.
    example: false
  onePerTenant:
    type: boolean
    default: false
    description: Indicates whether there is only one object of this type.
    example: false
  exportable:
    type: boolean
    default: false
    description: Indicates whether the object can be exported or is just a reference object.
    example: true
  rules:
    $ref: ./SpConfigRules.yaml
