openapi: 3.0.1
info:
  title: Identity Security Cloud API - Public Identities
  description: >-
    Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with
    greater scalability. We encourage you to join the SailPoint Developer Community forum at
    https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
  termsOfService: https://developer.sailpoint.com/discuss/tos
  contact:
    name: Developer Relations
    url: https://developer.sailpoint.com/discuss/api-help
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: v1
servers:
  - url: https://{tenant}.api.identitynow.com
    description: This is the production API server.
    variables:
      tenant:
        default: sailpoint
        description: This is the name of your tenant, typically your company's name.
  - url: https://{apiUrl}
    description: This is the versioned API server.
    variables:
      apiUrl:
        default: sailpoint.api.identitynow.com
        description: This is the api url of your tenant
tags:
  - name: Public Identities
    description: >
      Use this API in conjunction with [Public Identites
      Config](https://developer.sailpoint.com/docs/api/public-identities-config) to enable non-administrators to
      view identities' publicly visible attributes. 

      With this functionality in place, non-administrators can view identity attributes other than the default
      attributes (email, lifecycle state, and manager), depending on which identity attributes their organization
      administrators have made public. 

      This can be helpful for access approvers, certification reviewers, managers viewing their direct reports' access,
      and source owners viewing their tasks.
paths:
  /public-identities/v1:
    $ref: ./paths/public-identities-v1.yaml
security:
  - userAuth:
      - sp:scopes:all
