openapi: 3.0.1
info:
  title: Identity Security Cloud API - Personal Access Tokens
  description: >-
    Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with
    greater scalability. We encourage you to join the SailPoint Developer Community forum at
    https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
  termsOfService: https://developer.sailpoint.com/discuss/tos
  contact:
    name: Developer Relations
    url: https://developer.sailpoint.com/discuss/api-help
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: v1
servers:
  - url: https://{tenant}.api.identitynow.com
    description: This is the production API server.
    variables:
      tenant:
        default: sailpoint
        description: This is the name of your tenant, typically your company's name.
  - url: https://{apiUrl}
    description: This is the versioned API server.
    variables:
      apiUrl:
        default: sailpoint.api.identitynow.com
        description: This is the api url of your tenant
tags:
  - name: Personal Access Tokens
    description: >
      Use this API to implement personal access token (PAT) functionality. 

      With this functionality in place, users can use PATs as an alternative to passwords for authentication in Identity
      Security Cloud. 


      PATs embed user information into the client ID and secret. 

      This replaces the API clients' need to store and provide a username and password to establish a connection,
      improving Identity Security Cloud organizations' integration security. 


      In Identity Security Cloud, users can do the following to create and manage their PATs: Select the dropdown menu
      under their names, select Preferences, and then select Personal Access Tokens. 

      They must then provide a description about the token's purpose. 

      They can then select 'Create Token' at the bottom of the page to generate and view the Secret and Client ID. 


      Refer to [Managing Personal Access
      Tokens](https://documentation.sailpoint.com/saas/help/common/api_keys.html?h=token#generating-a-personal-access-token)
      for more information about PATs.
paths:
  /personal-access-tokens/v1:
    $ref: ./paths/personal-access-tokens-v1.yaml
  /personal-access-tokens/v1/{id}:
    $ref: ./paths/personal-access-tokens-v1-by-id.yaml
security:
  - userAuth:
      - sp:scopes:all
