openapi: 3.0.1
info:
  title: Identity Security Cloud API - Search Attribute Configuration
  description: >-
    Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with
    greater scalability. We encourage you to join the SailPoint Developer Community forum at
    https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
  termsOfService: https://developer.sailpoint.com/discuss/tos
  contact:
    name: Developer Relations
    url: https://developer.sailpoint.com/discuss/api-help
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: v1
servers:
  - url: https://{tenant}.api.identitynow.com
    description: This is the production API server.
    variables:
      tenant:
        default: sailpoint
        description: This is the name of your tenant, typically your company's name.
  - url: https://{apiUrl}
    description: This is the versioned API server.
    variables:
      apiUrl:
        default: sailpoint.api.identitynow.com
        description: This is the api url of your tenant
tags:
  - name: Search Attribute Configuration
    description: >
      Use this API to implement search attribute configuration functionality, along with
      [Search](https://developer.sailpoint.com/docs/api/search).

      With this functionality in place, administrators can create custom search attributes that and run extended
      searches based on those attributes to further narrow down their searches and get the information and insights they
      want. 


      Identity Security Cloud (ISC) enables organizations to store user data from across all their connected sources and
      manage the users' access, so the ability to query and filter that data is essential.  

      Its search goes through all those sources and finds the results quickly and specifically. 


      The search query is flexible - it can be very broad or very narrow. 

      The search only returns results for searchable objects it is filtering for. 

      The following objects are searchable: identities, roles, access profiles, entitlements, events, and account
      activities. 

      By default, no filter is applied, so a search for "Ad" returns both the identity "Adam.Archer" as well as the role
      "Administrator."


      Users can further narrow their results by using ISC's specific syntax and punctuation to structure their queries. 

      For example, the query "attributes.location:austin AND NOT manager.name:amanda.ross" returns all results
      associated with the Austin location, but it excludes those associated with the manager Amanda Ross.

      Refer to [Building a Search Query](https://documentation.sailpoint.com/saas/help/search/building-query.html) for
      more information about how to construct specific search queries. 


      Refer to [Search Attribute
      Configuration](https://developer.sailpoint.com/docs/extensibility/rules/rule-utility/#configuration-of-search-attributes-within-identity-security-cloud)
      for more information about ISC's search and its different possibilities. 


      With Search Attribute Configuration, administrators can create, manage, and run searches based on the attributes
      they want to search. 
paths:
  /accounts/v1/search-attribute-config:
    $ref: ./paths/accounts-v1-search-attribute-config.yaml
  /accounts/v1/search-attribute-config/{name}:
    $ref: ./paths/accounts-v1-search-attribute-config-by-name.yaml
security:
  - userAuth:
      - sp:scopes:all
