openapi: 3.0.1
info:
  title: Identity Security Cloud API - Access Model Metadata
  description: >-
    Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with
    greater scalability. We encourage you to join the SailPoint Developer Community forum at
    https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
  termsOfService: https://developer.sailpoint.com/discuss/tos
  contact:
    name: Developer Relations
    url: https://developer.sailpoint.com/discuss/api-help
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: v1
servers:
  - url: https://{tenant}.api.identitynow.com
    description: This is the production API server.
    variables:
      tenant:
        default: sailpoint
        description: This is the name of your tenant, typically your company's name.
  - url: https://{apiUrl}
    description: This is the versioned API server.
    variables:
      apiUrl:
        default: sailpoint.api.identitynow.com
        description: This is the api url of your tenant
tags:
  - name: Access Model Metadata
    description: >
      Use this API to create and manage metadata attributes for your Access Model.

      Access Model Metadata allows you to add contextual information to your ISC Access Model items using pre-defined
      metadata for risk, regulations, privacy levels, etc., or by creating your own metadata attributes to reflect the
      unique needs of your organization. This release of the API includes support for entitlement metadata. Support for
      role and access profile metadata will be introduced in a subsequent release.


      Common usages for Access Model metadata include:


      - Organizing and categorizing access items to make it easier for your users to search for and find the access
      rights they want to request, certify, or manage.


      - Providing richer information about access that is being acted on to allow stakeholders to make better decisions
      when approving, certifying, or managing access rights.


      - Identifying access that may requires additional approval requirements or be subject to more frequent review.
paths:
  /access-model-metadata/v1/attributes:
    $ref: ./paths/access-model-metadata-v1-attributes.yaml
  /access-model-metadata/v1/attributes/{key}:
    $ref: ./paths/access-model-metadata-v1-attributes-by-key.yaml
  /access-model-metadata/v1/attributes/{key}/values:
    $ref: ./paths/access-model-metadata-v1-attributes-by-key-values.yaml
  /access-model-metadata/v1/attributes/{key}/values/{value}:
    $ref: ./paths/access-model-metadata-v1-attributes-by-key-values-by-value.yaml
  /access-model-metadata/v1/bulk-update/filter:
    $ref: ./paths/access-model-metadata-v1-bulk-update-filter.yaml
  /access-model-metadata/v1/bulk-update/query:
    $ref: ./paths/access-model-metadata-v1-bulk-update-query.yaml
  /access-model-metadata/v1/bulk-update/ids:
    $ref: ./paths/access-model-metadata-v1-bulk-update-ids.yaml
security:
  - userAuth:
      - sp:scopes:all
