type: object
title: Source Entitlement Request Config
description: Entitlement Request Configuration
properties:
  accessRequestConfig:
    $ref: './SourceEntitlementAccessRequestConfig.yaml'
    description: Configuration for requesting access to entitlements
  revocationRequestConfig:
    $ref: './SourceEntitlementRevocationRequestConfig.yaml'
