openapi: 3.0.1
info:
  title: Identity Security Cloud API - Application Discovery
  description: >-
    Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with
    greater scalability. We encourage you to join the SailPoint Developer Community forum at
    https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
  termsOfService: https://developer.sailpoint.com/discuss/tos
  contact:
    name: Developer Relations
    url: https://developer.sailpoint.com/discuss/api-help
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: v1
servers:
  - url: https://{tenant}.api.identitynow.com
    description: This is the production API server.
    variables:
      tenant:
        default: sailpoint
        description: This is the name of your tenant, typically your company's name.
  - url: https://{apiUrl}
    description: This is the versioned API server.
    variables:
      apiUrl:
        default: sailpoint.api.identitynow.com
        description: This is the api url of your tenant
tags:
  - name: Application Discovery
    description: >
      Use this API to implement application discovery functionality. 

      With this functionality in place, you can discover applications within your Okta connector and receive connector
      recommendations by manually uploading application names.
paths:
  /sources/v1/{sourceId}/discover-applications:
    $ref: ./paths/sources-v1-by-sourceid-discover-applications.yaml
  /discovered-applications/v1:
    $ref: ./paths/discovered-applications-v1.yaml
  /manual-discover-applications-template/v1:
    $ref: ./paths/manual-discover-applications-template-v1.yaml
  /manual-discover-applications/v1:
    $ref: ./paths/manual-discover-applications-v1.yaml
security:
  - userAuth:
      - sp:scopes:all
