get:
  operationId: getCorrelationConfig
  tags:
    - Sources
  summary: Get source correlation configuration
  security:
    - userAuth: [idn:sources:read, idn:sources:manage]
  x-sailpoint-userLevels:
    - ORG_ADMIN
    - SOURCE_ADMIN
    - SOURCE_SUBADMIN
  description: >-
    This API returns the existing correlation configuration for a source specified by the
    given ID.
  parameters:
    - in: path
      name: id
      required: true
      x-sailpoint-resource-operation-id: listSources
      schema:
        type: string
      description: The source id
      example: 2c9180835d191a86015d28455b4a2329
  responses:
    '200':
      description: Correlation configuration for a source
      content:
        application/json:
          schema:
            $ref: '../schemas/CorrelationConfig.yaml'
    '400':
      $ref: '../responses/400.yaml'
    '401':
      $ref: '../responses/401.yaml'
    '403':
      $ref: '../responses/403.yaml'
    '404':
      $ref: '../responses/404.yaml'
    '429':
      $ref: '../responses/429.yaml'
    '500':
      $ref: '../responses/500.yaml'

put:
  operationId: putCorrelationConfig
  tags:
    - Sources
  summary: Update source correlation configuration
  security:
    - userAuth: [idn:sources:manage]
  x-sailpoint-userLevels:
    - ORG_ADMIN
    - SOURCE_ADMIN
    - SOURCE_SUBADMIN
  description: >-
    Replaces the correlation configuration for the source specified by the given ID with the
    configuration provided in the request body.
  parameters:
    - in: path
      name: id
      required: true
      x-sailpoint-resource-operation-id: listSources
      schema:
        type: string
      description: The source id
      example: 2c9180835d191a86015d28455b4a2329
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../schemas/CorrelationConfig.yaml'
  responses:
    '200':
      description: Updated correlation configuration for a source
      content:
        application/json:
          schema:
            $ref: '../schemas/CorrelationConfig.yaml'
    '400':
      $ref: '../responses/400.yaml'
    '401':
      $ref: '../responses/401.yaml'
    '403':
      $ref: '../responses/403.yaml'
    '404':
      $ref: '../responses/404.yaml'
    '429':
      $ref: '../responses/429.yaml'
    '500':
      $ref: '../responses/500.yaml'
