get:
  operationId: getEntitlementRequestConfig
  tags:
  - Entitlements
  summary: Get entitlement request config
  description: This API returns the entitlement request config for a specified entitlement.
  security:
  - userAuth:
    - idn:entitlement:read
    - idn:entitlement:manage
  x-sailpoint-userLevels:
    - ORG_ADMIN
    - SOURCE_SUBADMIN
    - SOURCE_ADMIN
  parameters:
  - in: path
    name: id
    schema:
      type: string
    required: true
    x-sailpoint-resource-operation-id: listEntitlements
    description: Entitlement Id
    example: 2c91808874ff91550175097daaec161c
  - name: X-SailPoint-Experimental
    in: header
    description: Use this header to enable this experimental API.
    example: true
    schema:
      type: string
      default: true
    required: true
  responses:
    '200':
      description: An Entitlement Request Config
      content:
        application/json:
          schema:
            $ref: ../schemas/EntitlementRequestConfig.yaml
          example:
            accessRequestConfig:
              requestCommentRequired: true
              denialCommentRequired: true
              reauthorizationRequired: false
              approvalSchemes:
              - approverType: ENTITLEMENT_OWNER
                approverId: null
              - approverType: SOURCE_OWNER
                approverId: null
              - approverType: MANAGER
                approverId: null
              - approverType: GOVERNANCE_GROUP
                approverId: 46c79819-a69f-49a2-becb-12c971ae66c6
            revocationRequestConfig:
              approvalSchemes:
              - approverType: ENTITLEMENT_OWNER
                approverId: null
              - approverType: SOURCE_OWNER
                approverId: null
              - approverType: MANAGER
                approverId: null
              - approverType: GOVERNANCE_GROUP
                approverId: 46c79819-a69f-49a2-becb-12c971ae66c6
    '400':
      $ref: ../responses/400.yaml
    '401':
      $ref: ../responses/401.yaml
    '403':
      $ref: ../responses/403.yaml
    '404':
      $ref: ../responses/404.yaml
    '429':
      $ref: ../responses/429.yaml
    '500':
      $ref: ../responses/500.yaml
put:
  operationId: putEntitlementRequestConfig
  tags:
  - Entitlements
  summary: Replace entitlement request config
  description: This API replaces the entitlement request config for a specified entitlement.
  security:
  - userAuth:
    - idn:entitlement:manage
  x-sailpoint-userLevels:
  - ORG_ADMIN
  - SOURCE_SUBADMIN
  - SOURCE_ADMIN
  parameters:
  - name: id
    in: path
    description: Entitlement ID
    required: true
    x-sailpoint-resource-operation-id: listEntitlements
    schema:
      type: string
      example: 2c91808a7813090a017814121e121518
  - name: X-SailPoint-Experimental
    in: header
    description: Use this header to enable this experimental API.
    example: true
    schema:
      type: string
      default: true
    required: true
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../schemas/EntitlementRequestConfig.yaml
  responses:
    '200':
      description: Responds with the entitlement request config as updated.
      content:
        application/json:
          schema:
            $ref: ../schemas/EntitlementRequestConfig.yaml
          example:
            accessRequestConfig:
              requestCommentRequired: true
              denialCommentRequired: true
              approvalSchemes:
              - approverType: ENTITLEMENT_OWNER
                approverId: null
              - approverType: SOURCE_OWNER
                approverId: null
              - approverType: MANAGER
                approverId: null
              - approverType: GOVERNANCE_GROUP
                approverId: 46c79819-a69f-49a2-becb-12c971ae66c6
            revocationRequestConfig:
              approvalSchemes:
              - approverType: ENTITLEMENT_OWNER
                approverId: null
              - approverType: SOURCE_OWNER
                approverId: null
              - approverType: MANAGER
                approverId: null
              - approverType: GOVERNANCE_GROUP
                approverId: 46c79819-a69f-49a2-becb-12c971ae66c6
    '400':
      $ref: ../responses/400.yaml
    '401':
      $ref: ../responses/401.yaml
    '403':
      $ref: ../responses/403.yaml
    '404':
      $ref: ../responses/404.yaml
    '429':
      $ref: ../responses/429.yaml
    '500':
      $ref: ../responses/500.yaml
