post:
  operationId: testApplicationMapping
  tags:
    - SaaS Management
  summary: Test saas management application mapping
  description: >-
    This API tests if accounts on IdentityNow match those on the mapped SaaS Management Application,
    or 404 if not mapped.

    A token with ORG_ADMIN, SOURCE_ADMIN or SOURCE_SUBADMIN authority is required to call this API.
  parameters:
    - in: path
      name: id
      schema:
        type: string
      required: true
      x-sailpoint-resource-operation-id: listSources
      description: The IdentityNow source ID
      example: 2c9180866166b5b0016167c32ef31a66
  responses:
    '200':
      description: SaaS Management application object with the updated test result.
      content:
        application/json:
          schema:
            $ref: '../../beta/schemas/SaasManagementApplication.yaml'
    '400':
      $ref: '../responses/400.yaml'
    '401':
      $ref: '../responses/401.yaml'
    '403':
      $ref: '../responses/403.yaml'
    '404':
      $ref: '../responses/404.yaml'
    '429':
      $ref: '../responses/429.yaml'
    '500':
      $ref: '../responses/500.yaml'
