openapi: 3.0.1
info:
  title: Identity Security Cloud API - Account Activities
  description: >-
    Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with
    greater scalability. We encourage you to join the SailPoint Developer Community forum at
    https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
  termsOfService: https://developer.sailpoint.com/discuss/tos
  contact:
    name: Developer Relations
    url: https://developer.sailpoint.com/discuss/api-help
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: v1
servers:
  - url: https://{tenant}.api.identitynow.com
    description: This is the production API server.
    variables:
      tenant:
        default: sailpoint
        description: This is the name of your tenant, typically your company's name.
  - url: https://{apiUrl}
    description: This is the versioned API server.
    variables:
      apiUrl:
        default: sailpoint.api.identitynow.com
        description: This is the api url of your tenant
tags:
  - name: Account Activities
    description: >
      Use this API to implement account activity tracking functionality.

      With this functionality in place, users can track source account activity in Identity Security Cloud, which
      greatly improves traceability in the system. 


      An account activity refers to a log of each action performed on a source account. This is useful for auditing the
      changes performed on an account throughout its life. 

      In Identity Security Cloud's Search, users can search for account activities and select the activity's row to get
      an overview of the activity's account action and view its progress, its involved sources, and its most basic
      metadata, such as the identity requesting the option and the recipient. 


      Account activity includes most actions Identity Security Cloud completes on source accounts. Users can search in
      Identity Security Cloud for the following account action types: 


      - Access Request: These include any access requests the source account is involved in. 


      - Account Attribute Updates: These include updates to a single attribute on an account on a source. 


      - Account State Update: These include locking or unlocking actions on an account on a source. 


      - Certification: These include actions removing an entitlement from an account on a source as a result of the
      entitlement's revocation during a certification.


      - Cloud Automated `Lifecyclestate`: These include automated lifecycle state changes that result in a source
      account's correlated identity being assigned to a different lifecycle state. 

      Identity Security Cloud replaces the `Lifecyclestate` variable with the name of the lifecycle state it has moved
      the account's identity to. 


      - Identity Attribute Update: These include updates to a source account's correlated identity attributes as the
      result of a provisioning action. 

      When you update an identity attribute that also updates an identity's lifecycle state, the cloud automated
      `Lifecyclestate` event also displays.

      Account Activity does not include attribute updates that occur as a result of aggregation.


      - Identity Refresh: These include correlated identity refreshes that occur for an account on a source whenever the
      account's correlated identity profile gets a new role or updates. 

      These also include refreshes that occur whenever Identity Security Cloud assigns an application to the account's
      correlated identity based on the application's being assigned to All Users From Source or Specific Users From
      Source. 


      - Lifecycle State Refresh: These include the actions that took place when a lifecycle state changed. This event
      only occurs after a cloud automated `Lifecyclestate` change or a lifecycle state change. 


      - Lifecycle State Change: These include the account activities that result from an identity's manual assignment to
      a null lifecycle state.


      - Password Change: These include password changes on sources.


      Refer to [Account Activity](https://documentation.sailpoint.com/saas/help/search/index.html#account-activity) for
      more information about account activities.
paths:
  /account-activities/v1:
    $ref: ./paths/account-activities-v1.yaml
  /account-activities/v1/{id}:
    $ref: ./paths/account-activities-v1-by-id.yaml
security:
  - userAuth:
      - sp:scopes:all
