openapi: 3.0.1
info:
  title: Identity Security Cloud API - Password Policies
  description: >-
    Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with
    greater scalability. We encourage you to join the SailPoint Developer Community forum at
    https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
  termsOfService: https://developer.sailpoint.com/discuss/tos
  contact:
    name: Developer Relations
    url: https://developer.sailpoint.com/discuss/api-help
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: v1
servers:
  - url: https://{tenant}.api.identitynow.com
    description: This is the production API server.
    variables:
      tenant:
        default: sailpoint
        description: This is the name of your tenant, typically your company's name.
  - url: https://{apiUrl}
    description: This is the versioned API server.
    variables:
      apiUrl:
        default: sailpoint.api.identitynow.com
        description: This is the api url of your tenant
tags:
  - name: Password Policies
    description: >
      Use these APIs to implement password policies functionality.

      These APIs allow you to define the policy parameters for choosing passwords.


      IdentityNow comes with a default policy that you can modify to define the password requirements your users must
      meet to log in to IdentityNow, such as requiring a minimum password length, including special characters, and
      disallowing certain patterns.

      If you have licensed Password Management, you can create additional password policies beyond the default one to
      manage passwords for supported sources in your org.


      In the Identity Security Cloud Admin panel, administrators can use the Password Mgmt dropdown menu to select Sync
      Groups.

      Refer to [Managing Password
      Policies](https://documentation.sailpoint.com/saas/help/pwd/pwd_policies/pwd_policies.html) for more information
      about password policies.
paths:
  /password-policies/v1/{id}:
    $ref: ./paths/password-policies-v1-by-id.yaml
  /password-policies/v1:
    $ref: ./paths/password-policies-v1.yaml
security:
  - userAuth:
      - sp:scopes:all
