type: object
title: Public Identity Attribute Config
description: >-
  Used to map an attribute key for an Identity to its display name.
properties:
  key:
    type: string
    description: The attribute key
    example: "country"
  name:
    type: string
    description: The attribute display name
    example: "Country"
