openapi: 3.0.1
info:
  title: Identity Security Cloud API - Org Config
  description: >-
    Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with
    greater scalability. We encourage you to join the SailPoint Developer Community forum at
    https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
  termsOfService: https://developer.sailpoint.com/discuss/tos
  contact:
    name: Developer Relations
    url: https://developer.sailpoint.com/discuss/api-help
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: v1
servers:
  - url: https://{tenant}.api.identitynow.com
    description: This is the production API server.
    variables:
      tenant:
        default: sailpoint
        description: This is the name of your tenant, typically your company's name.
  - url: https://{apiUrl}
    description: This is the versioned API server.
    variables:
      apiUrl:
        default: sailpoint.api.identitynow.com
        description: This is the api url of your tenant
tags:
  - name: Org Config
    description: |
      Use this API to implement organization configuration functionality. 
      Administrators can use this functionality to manage organization settings, such as time zones. 
paths:
  /org-config/v1:
    $ref: ./paths/org-config-v1.yaml
  /org-config/v1/valid-time-zones:
    $ref: ./paths/org-config-v1-valid-time-zones.yaml
security:
  - userAuth:
      - sp:scopes:all
