required: true
content:
  application/json:
    schema:
      type: object
      properties:
        profiles:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                format: uuid