type : object
title: Approval Reminder And Escalation Config
description: |
  Configuration for approval reminder and escalation behavior. Important: Modifying this object will override the sp-approval service's reminderConfig and escalationConfig settings. Changes made here take precedence over any configuration set directly in the sp-approval service.
properties:
  daysUntilEscalation:
    type: integer
    description: Number of days to wait before the first reminder. If no reminders are configured, then this is the number of days to wait before escalation.
    format: int32
    example: 0
    nullable: true
  daysBetweenReminders:
    type: integer
    description: Number of days to wait between reminder notifications.
    format: int32
    example: 0
    nullable: true
  maxReminders:
    type: integer
    description: Maximum number of reminder notifications to send to the reviewer before approval escalation. The maximum allowed value is 20.
    format: int32
    minimum: 0
    maximum: 20
    example: 1
    nullable: true
  fallbackApproverRef:
    $ref: './IdentityReferenceWithNameAndEmail.yaml'