type: object
description: The response body of a Reassignment Configuration for a single identity
properties:
  identity:
    $ref: 'Identity.yaml'
  configDetails:
    type: array
    description: Details of how work should be reassigned for an Identity
    items:
      $ref: 'ConfigurationDetailsResponse.yaml'
