get:
  operationId: getAuthOrgSessionConfig
  tags:
    - Global Tenant Security Settings
  summary: Get auth org session configuration.
  description: >-
    This API returns the details of an org's session auth configuration.
  security:
    - userAuth: [ sp:auth-org:read ]
  responses:
    "200":
      description: Session configuration for the tenant's auth org.
      content:
        application/json:
          schema:
            $ref: "../schemas/SessionConfiguration.yaml"
    "400":
      $ref: "../responses/400.yaml"
    "401":
      $ref: "../responses/401.yaml"
    "403":
      $ref: "../responses/403.yaml"
    "404":
      $ref: "../responses/404.yaml"
    "429":
      $ref: "../responses/429.yaml"
    "500":
      $ref: "../responses/500.yaml"
patch:
  operationId: patchAuthOrgSessionConfig
  tags:
    - Global Tenant Security Settings
  summary: Update auth org session configuration
  description: >-
    This API updates an existing session configuration for an org using PATCH.
  security:
    - userAuth: [ sp:auth-org:manage ]
  x-sailpoint-userLevels:
    - ORG_ADMIN
    - HELPDESK
  requestBody:
    required: true
    description: |
      A list of auth org session configuration update operations according to
      the [JSON Patch](https://tools.ietf.org/html/rfc6902) standard.

      Ensures that the patched Session Config conforms to certain logical
      guidelines, which are:
        `1. maxSessionTime >= 1 && maxSessionTime <= 10080 (1 week)
        2. maxIdleTime >= 1 && maxIdleTime <= 1440 (1 day)
        3. maxSessionTime must have a greater duration than maxIdleTime.`
    content:
      application/json-patch+json:
        schema:
          type: array
          items:
            $ref: "../schemas/JsonPatchOperation.yaml"
        example:
          - op: "replace"
            path: "/rememberMe"
            value: true,
          - op: "add"
            path: "/maxSessionTime"
            value: 480
  responses:
    "200":
      description: Updated Auth Org session configuration.
      content:
        application/json:
          schema:
            $ref: "../schemas/SessionConfiguration.yaml"
    "400":
      $ref: "../responses/400.yaml"
    "401":
      $ref: "../responses/401.yaml"
    "403":
      $ref: "../responses/403.yaml"
    "404":
      $ref: "../responses/404.yaml"
    "429":
      $ref: "../responses/429.yaml"
    "500":
      $ref: "../responses/500.yaml"
