get:
  operationId: getApplicationForSource
  tags:
    - SaaS Management
  summary: Saas management application for source
  description: >-
    This API returns the mapped SaaS Management application for an IdentityNow source ID or 404 if not mapped.

    A token with ORG_ADMIN, SOURCE_ADMIN or SOURCE_SUBADMIN authority is required to call this API.
  parameters:
    - in: path
      name: id
      schema:
        type: string
      required: true
      x-sailpoint-resource-operation-id: listSources
      description: The IdentityNow source ID
      example: 2c9180866166b5b0016167c32ef31a66
  responses:
    '200':
      description: SaaS Management application for source, if source is mapped.
      content:
        application/json:
          schema:
            $ref: '../../beta/schemas/SaasManagementApplication.yaml'
    '400':
      $ref: '../../v3/responses/400.yaml'
    '401':
      $ref: '../../v3/responses/401.yaml'
    '403':
      $ref: '../../v3/responses/403.yaml'
    '404':
      $ref: '../../v3/responses/404.yaml'
    '429':
      $ref: '../../v3/responses/429.yaml'
    '500':
      $ref: '../../v3/responses/500.yaml'
