openapi: 3.0.1
info:
  title: Identity Security Cloud API - Approvals
  description: >-
    Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with
    greater scalability. We encourage you to join the SailPoint Developer Community forum at
    https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
  termsOfService: https://developer.sailpoint.com/discuss/tos
  contact:
    name: Developer Relations
    url: https://developer.sailpoint.com/discuss/api-help
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: v1
servers:
  - url: https://{tenant}.api.identitynow.com
    description: This is the production API server.
    variables:
      tenant:
        default: sailpoint
        description: This is the name of your tenant, typically your company's name.
  - url: https://{apiUrl}
    description: This is the versioned API server.
    variables:
      apiUrl:
        default: sailpoint.api.identitynow.com
        description: This is the api url of your tenant
tags:
  - name: Approvals
    description: >
      Use this API to implement approval functionality. With this functionality in place, you can get generic approvals
      and modify them. 


      The main advantages this API has vs [Access Request
      Approvals](https://developer.sailpoint.com/docs/api/v2025/access-request-approvals) are that you can use it to get
      generic approvals individually or in batches and make changes to those approvals. 
paths:
  /generic-approvals/v1:
    $ref: ./paths/generic-approvals-v1.yaml
  /generic-approvals/v1/{id}:
    $ref: ./paths/generic-approvals-v1-by-id.yaml
  /generic-approvals/v1/{id}/approve:
    $ref: ./paths/generic-approvals-v1-by-id-approve.yaml
  /generic-approvals/v1/{id}/attributes:
    $ref: ./paths/generic-approvals-v1-by-id-attributes.yaml
  /generic-approvals/v1/{id}/comments:
    $ref: ./paths/generic-approvals-v1-by-id-comments.yaml
  /generic-approvals/v1/{id}/reassign:
    $ref: ./paths/generic-approvals-v1-by-id-reassign.yaml
  /generic-approvals/v1/{id}/reject:
    $ref: ./paths/generic-approvals-v1-by-id-reject.yaml
  /generic-approvals/v1/{id}/cancel:
    $ref: ./paths/generic-approvals-v1-by-id-cancel.yaml
  /generic-approvals/v1/config/{id}:
    $ref: ./paths/generic-approvals-v1-config-by-id.yaml
  /generic-approvals/v1/config/{id}/{scope}:
    $ref: ./paths/generic-approvals-v1-config-by-id-by-scope.yaml
  /generic-approvals/v1/bulk-approve:
    $ref: ./paths/generic-approvals-v1-bulk-approve.yaml
  /generic-approvals/v1/bulk-reject:
    $ref: ./paths/generic-approvals-v1-bulk-reject.yaml
  /generic-approvals/v1/bulk-cancel:
    $ref: ./paths/generic-approvals-v1-bulk-cancel.yaml
  /generic-approvals/v1/bulk-reassign:
    $ref: ./paths/generic-approvals-v1-bulk-reassign.yaml
security:
  - userAuth:
      - sp:scopes:all
