patch:
  operationId: updateScheduledActionV1
  security:
  - userAuth:
    - sp:config-scheduled-action:manage
  x-sailpoint-userLevels:
  - ORG_ADMIN
  tags:
  - Configuration Hub
  summary: Update scheduled action
  description: This API updates an existing scheduled action using JSON Patch format.
  parameters:
  - in: path
    name: id
    schema:
      type: string
    required: true
    description: The ID of the scheduled action.
    example: 0f11f2a4-7c94-4bf3-a2bd-742580fe3bde
    x-sailpoint-resource-operation-id: listScheduledActionsV1
  requestBody:
    description: The JSON Patch document containing the changes to apply to the scheduled action.
    required: true
    content:
      application/json-patch+json:
        schema:
          $ref: ../../shared/schemas/jsonpatch.yaml
        example:
        - op: replace
          path: /content/name
          value: Updated Backup Name
        - op: replace
          path: /cronString
          value: 0 0 9 * * ?
  responses:
    '200':
      description: The updated scheduled action.
      content:
        application/json:
          schema:
            $ref: ../schemas/scheduledactionresponse.yaml
          example:
            id: 0f11f2a4-7c94-4bf3-a2bd-742580fe3bde
            created: '2024-08-16T14:16:58.389Z'
            jobType: BACKUP
            content:
              name: Updated Backup Name
              backupOptions:
                includeTypes:
                - SOURCE
                - IDENTITY
                objectOptions:
                  SOURCE:
                    includedNames:
                    - Source1
                    - Source2
            startTime: '2024-08-16T14:16:58.389Z'
            cronString: 0 0 9 * * ?
    '400':
      $ref: ../../shared/responses/400.yaml
    '401':
      $ref: ../../shared/responses/401.yaml
    '403':
      $ref: ../../shared/responses/403.yaml
    '404':
      $ref: ../../shared/responses/404.yaml
    '429':
      $ref: ../../shared/responses/429.yaml
    '500':
      $ref: ../../shared/responses/500.yaml
delete:
  operationId: deleteScheduledActionV1
  security:
  - userAuth:
    - sp:config-scheduled-action:manage
  x-sailpoint-userLevels:
  - ORG_ADMIN
  tags:
  - Configuration Hub
  summary: Delete scheduled action
  description: This API deletes an existing scheduled action.
  parameters:
  - in: path
    name: id
    schema:
      type: string
    required: true
    description: The ID of the scheduled action.
    example: 0f11f2a4-7c94-4bf3-a2bd-742580fe3bde
    x-sailpoint-resource-operation-id: listScheduledActionsV1
  responses:
    '204':
      $ref: ../../shared/responses/204.yaml
    '400':
      $ref: ../../shared/responses/400.yaml
    '401':
      $ref: ../../shared/responses/401.yaml
    '403':
      $ref: ../../shared/responses/403.yaml
    '404':
      $ref: ../../shared/responses/404.yaml
    '429':
      $ref: ../../shared/responses/429.yaml
    '500':
      $ref: ../../shared/responses/500.yaml
