openapi: 3.0.1
info:
  title: Identity Security Cloud API - UI Metadata
  description: >-
    Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with
    greater scalability. We encourage you to join the SailPoint Developer Community forum at
    https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
  termsOfService: https://developer.sailpoint.com/discuss/tos
  contact:
    name: Developer Relations
    url: https://developer.sailpoint.com/discuss/api-help
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: v1
servers:
  - url: https://{tenant}.api.identitynow.com
    description: This is the production API server.
    variables:
      tenant:
        default: sailpoint
        description: This is the name of your tenant, typically your company's name.
  - url: https://{apiUrl}
    description: This is the versioned API server.
    variables:
      apiUrl:
        default: sailpoint.api.identitynow.com
        description: This is the api url of your tenant
tags:
  - name: UI Metadata
    description: >-
      API for managing UI Metadata. Use this API to manage metadata about your User Interface.

      For example you can set the iFrameWhitelist parameter to permit another domain to encapsulate IDN within an iframe
      or set the usernameEmptyText to change the placeholder text for Username on your tenant's login screen.
paths:
  /ui-metadata/v1/tenant:
    $ref: ./paths/ui-metadata-v1-tenant.yaml
security:
  - userAuth:
      - sp:scopes:all
