description: Expected response to a valid request
content:
  application/json:
    schema:
      type: object
      properties:
        workflow:
          type: object
          $ref: '../schemas/GET/WorkflowSession.yaml'