get:
  summary: Get access model metadata value
  description: Get single Access Model Metadata Attribute Value
  tags:
  - Access Model Metadata
  operationId: getAccessModelMetadataAttributeValueV1
  security:
  - userAuth:
    - idn:access-model-metadata:read
    - idn:access-model-metadata:manage
  - applicationAuth:
    - idn:access-model-metadata:read
    - idn:access-model-metadata:manage
  x-sailpoint-userLevels:
  - ORG_ADMIN
  parameters:
  - name: key
    in: path
    required: true
    x-sailpoint-resource-operation-id: listAccessModelMetadataAttributeV1
    schema:
      type: string
    description: Technical name of the Attribute.
    example: iscPrivacy
  - name: value
    in: path
    required: true
    x-sailpoint-resource-operation-id: listAccessModelMetadataAttributeValueV1
    schema:
      type: string
    description: Technical name of the Attribute value.
    example: public
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../../shared/schemas/attributevaluedto.yaml
    '400':
      $ref: ../../shared/responses/400.yaml
    '401':
      $ref: ../../shared/responses/401.yaml
    '403':
      $ref: ../../shared/responses/403.yaml
    '404':
      $ref: ../../shared/responses/404.yaml
    '429':
      $ref: ../../shared/responses/429.yaml
    '500':
      $ref: ../../shared/responses/500.yaml
patch:
  summary: Update access model metadata value
  description: |
    Update an existing Access Model Metadata Attribute Value.    
    The following fields are patchable: **name**
  operationId: updateAccessModelMetadataAttributeValueV1
  tags:
  - Access Model Metadata
  security:
  - userAuth:
    - idn:access-model-metadata:update
  - applicationAuth:
    - idn:access-model-metadata:update
  x-sailpoint-userLevels:
  - ORG_ADMIN
  parameters:
  - name: key
    in: path
    required: true
    x-sailpoint-resource-operation-id: listAccessModelMetadataAttributeV1
    schema:
      type: string
    description: Technical name of the Attribute.
    example: iscPrivacy
  - name: value
    in: path
    required: true
    x-sailpoint-resource-operation-id: listAccessModelMetadataAttributeValueV1
    schema:
      type: string
    description: Technical name of the Attribute value.
    example: public
  requestBody:
    required: true
    description: JSON Patch array to apply
    content:
      application/json-patch+json:
        schema:
          type: array
          items:
            $ref: ../../shared/schemas/jsonpatchoperation.yaml
  responses:
    '200':
      description: OK - Attribute value updated successfully
      content:
        application/json:
          schema:
            $ref: ../../shared/schemas/attributevaluedto.yaml
    '400':
      $ref: ../../shared/responses/400.yaml
    '401':
      $ref: ../../shared/responses/401.yaml
    '403':
      $ref: ../../shared/responses/403.yaml
    '404':
      $ref: ../../shared/responses/404.yaml
    '429':
      $ref: ../../shared/responses/429.yaml
    '500':
      $ref: ../../shared/responses/500.yaml
