openapi: 3.0.1
info:
  title: Identity Security Cloud API - SIM Integrations
  description: >-
    Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with
    greater scalability. We encourage you to join the SailPoint Developer Community forum at
    https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
  termsOfService: https://developer.sailpoint.com/discuss/tos
  contact:
    name: Developer Relations
    url: https://developer.sailpoint.com/discuss/api-help
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: v1
servers:
  - url: https://{tenant}.api.identitynow.com
    description: This is the production API server.
    variables:
      tenant:
        default: sailpoint
        description: This is the name of your tenant, typically your company's name.
  - url: https://{apiUrl}
    description: This is the versioned API server.
    variables:
      apiUrl:
        default: sailpoint.api.identitynow.com
        description: This is the api url of your tenant
tags:
  - name: SIM Integrations
    description: >
      Use this API to administer IdentityNow's Service Integration Module, or SIM integration with ServiceNow, so that
      it converts IdentityNow provisioning actions into tickets in ServiceNow.


      ServiceNow is a software platform that supports IT service management and automates common business processes for
      requesting and fulfilling service requests across a business enterprise.


      You must have an IdentityNow ServiceNow ServiceDesk license to use this integration. Contact your Customer Success
      Manager for more information.


      Service Desk integration for IdentityNow and in deprecation - not available for new implementation, as of July
      21st, 2021. As per SailPoint's [support
      policy](https://community.sailpoint.com/t5/Connector-Directory/SailPoint-Support-Policy-for-Connectivity/ta-p/79422),
      all existing SailPoint IdentityNow customers using this legacy integration will be supported until July 2022.
paths:
  /sim-integrations/v1/{id}:
    $ref: ./paths/sim-integrations-v1-by-id.yaml
  /sim-integrations/v1/{id}/beforeProvisioningRule:
    $ref: ./paths/sim-integrations-v1-by-id-beforeprovisioningrule.yaml
  /sim-integrations/v1:
    $ref: ./paths/sim-integrations-v1.yaml
security:
  - userAuth:
      - sp:scopes:all
