required: true
content:
  application/json:
    schema:
      type: object
      properties:
        profiles:
          type: array
          items:
            $ref: "../../schemas/POST/Profile.yaml"