description: List of discovered applications
value:
  - id: "09d88a67-bae8-422c-a09b-f7a72f5ab032"
    name: "Example App"
    discoverySource: "csv"
    discoveredVendor: "Example Vendor"
    description: "An application for managing examples."
    recommendedConnectors: ["ConnectorA", "ConnectorB"]
    discoveredAt: "2023-07-01T12:00:00Z"
    createdAt: "2024-06-01T12:00:00Z"
    status: "ACTIVE"
  - id: "59310a1e-0d8f-42fa-95aa-b82b263de7f6"
    name: "Sample Tracker"
    discoverySource: "Okta SaaS"
    discoveredVendor: "Sample Vendor"
    description: "A tool for monitoring and managing samples."
    recommendedConnectors: ["ConnectorC", "ConnectorD"]
    discoveredAt: "2023-08-15T08:00:00Z"
    createdAt: "2024-05-20T08:00:00Z"
    status: "ACTIVE"
  - id: "dfe675cb-f689-475f-99f1-49e348449867"
    name: "Demo Manager"
    discoverySource: "Okta SaaS"
    discoveredVendor: "Demo Provider"
    description: "Software to demonstrate basic functionalities."
    recommendedConnectors: ["ConnectorE", "ConnectorF"]
    discoveredAt: "2023-09-10T15:00:00Z"
    createdAt: "2024-07-03T15:00:00Z"
    status: "ACTIVE"
