get:
  operationId: getAccessRequestConfigV2
  security:
  - userAuth:
    - idn:access-request-config:read
  x-sailpoint-userLevels:
  - ORG_ADMIN
  - SOURCE_ADMIN
  - SOURCE_SUBADMIN
  - USER
  summary: Get access request configuration
  tags:
  - Access Requests
  description: This endpoint returns the current access-request configuration.
  responses:
    '200':
      description: Access Request Configuration Details.
      content:
        application/json:
          schema:
            $ref: ../schemas/accessrequestconfigv2.yaml
    '400':
      $ref: ../../shared/responses/400.yaml
    '401':
      $ref: ../../shared/responses/401.yaml
    '403':
      $ref: ../../shared/responses/403.yaml
    '429':
      $ref: ../../shared/responses/429.yaml
    '500':
      $ref: ../../shared/responses/500.yaml
put:
  operationId: setAccessRequestConfigV2
  security:
  - userAuth:
    - idn:access-request-config:manage
  x-sailpoint-userLevels:
  - ORG_ADMIN
  summary: Update access request configuration
  tags:
  - Access Requests
  description: This endpoint replaces the current access-request configuration.
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../schemas/accessrequestconfigv2.yaml
  responses:
    '200':
      description: Access Request Configuration Details.
      content:
        application/json:
          schema:
            $ref: ../schemas/accessrequestconfigv2.yaml
    '400':
      $ref: ../../shared/responses/400.yaml
    '401':
      $ref: ../../shared/responses/401.yaml
    '403':
      $ref: ../../shared/responses/403.yaml
    '429':
      $ref: ../../shared/responses/429.yaml
    '500':
      $ref: ../../shared/responses/500.yaml
