get:
  security:
  - userAuth:
    - sp:approvals:read
  x-sailpoint-userLevels:
  - APPROVAL_OWNER
  operationId: getApprovalsConfigV1
  tags:
  - Approvals
  summary: Get Approval Config
  description: Retrieves a singular approval configuration that matches the given ID
  parameters:
  - in: path
    name: id
    required: true
    schema:
      type: string
    description: >-
      The id of the object the config applies to, for example one of the following: [(approvalID), (roleID),
      (entitlementID), (accessProfileID), "ENTITLEMENT_DESCRIPTIONS", "ACCESS_REQUEST_APPROVAL",
      "ACCOUNT_CREATE_APPROVAL_REQUEST", "ACCOUNT_DELETE_APPROVAL_REQUEST", "MACHINE_ACCOUNT_CREATE_APPROVAL_REQUEST",
      "MACHINE_ACCOUNT_DELETE_APPROVAL_REQUEST", (tenantID)]
    example: 1.2345678901234566e+31
    x-sailpoint-resource-operation-id: getApprovals
  responses:
    '200':
      description: Approval object
      content:
        application/json:
          schema:
            $ref: ../schemas/approvalconfig.yaml
    '400':
      $ref: ../../shared/responses/400.yaml
    '401':
      $ref: ../../shared/responses/401.yaml
    '403':
      $ref: ../../shared/responses/403.yaml
    '429':
      $ref: ../../shared/responses/429.yaml
    '500':
      $ref: ../../shared/responses/500.yaml
