openapi: 3.0.1
info:
  title: Identity Security Cloud API - Source Usages
  description: >-
    Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with
    greater scalability. We encourage you to join the SailPoint Developer Community forum at
    https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
  termsOfService: https://developer.sailpoint.com/discuss/tos
  contact:
    name: Developer Relations
    url: https://developer.sailpoint.com/discuss/api-help
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: v1
servers:
  - url: https://{tenant}.api.identitynow.com
    description: This is the production API server.
    variables:
      tenant:
        default: sailpoint
        description: This is the name of your tenant, typically your company's name.
  - url: https://{apiUrl}
    description: This is the versioned API server.
    variables:
      apiUrl:
        default: sailpoint.api.identitynow.com
        description: This is the api url of your tenant
tags:
  - name: Source Usages
    description: >
      Use this API to implement source usage insight functionality.

      With this functionality in place, administrators can gather information and insights about how their tenants'
      sources are being used.

      This allows organizations to get the information they need to start optimizing and securing source usage.
paths:
  /source-usages/v1/{sourceId}/status:
    $ref: ./paths/source-usages-v1-by-sourceid-status.yaml
  /source-usages/v1/{sourceId}/summaries:
    $ref: ./paths/source-usages-v1-by-sourceid-summaries.yaml
security:
  - userAuth:
      - sp:scopes:all
