name: PR Preview Link Check

on:
  issue_comment:
    types: [created, edited]

permissions:
  contents: read
  issues: write
  pull-requests: read

jobs:
  link-check:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        working-directory: scripts
        run: bun install

      - name: Run preview link check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: scripts
        run: bun run crawl.js


