name: Purge Cache

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Checkout custom cloudflare purge action
        uses: actions/checkout@v2
        with:
          repository: sailpoint-oss/cloudflare-purge-action-hosts
          path: cloudflare-purge-action-hosts
          ref: master
      - name: Cloudflare Purge Cache
        uses: ./cloudflare-purge-action-hosts/
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          SUBDOMAINS: '["developer.sailpoint.com"]'