summary: Expiration
value:
  clientId: 3a38a51992e8445ab51a549c0a70ee66
  expiration: "2024-11-06T01:31:08.013164Z"
  rootLevel: INFO
  logLevels:
    sailpoint.connector.ADLDAPConnector: TRACE
    sailpoint.connector.JDBCConnector: DEBUG